name: todo_list_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path: ^1.8.1
  intl: ^0.18.1
  get_it: ^7.2.0
  http: ^0.13.5
  fluttertoast: ^8.2.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.0.15
  date_picker_timeline: ^1.2.3
  smooth_page_indicator: ^1.0.0+2
  flutter_local_notifications: ^13.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_staggered_animations: ^1.1.1
  get: ^4.5.1
  get_storage: ^2.0.3
  rxdart: ^0.27.5
  hexcolor: ^3.0.1






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/